title: skills-github-pages-yaml
author: Michael Baker (prompt.mike@gmail.com)
description: Default GitHub Pages site created by completing the GitHub Skills: Pages course. Demonstrates ability to configure repository settings, enable GitHub Pages, manage branches, and deploy a basic static site from source.
theme: minima
